### ISSUE TITLE
Licence

### ISSUE THREAD

**Issue by PeteLawler** [amotoki/virtinst-scripts#1]
Hi!
Just wondering what licence you intended to release this as. I've substantially ported it for Debian but without an MIT or GPL etc. licence, I can't really fork and etc.

Hope you can help.

p.

**Comment by amotoki** [comment]
Sorry for late.

Thanks for asking. My intention is just one of open source licenses like Apache 2 license or GPL on these scripts. I have no strong preference. 

One question. You said MIT or GPL is required. What is the limitations on BSD or Apache 2 license. This is just my curiosity.

**Comment by PeteLawler** [comment]
I only mentioned MIT and GPL as examples, and didn't intend to indicate a preference. Any licence where I can easily fork and publish changes for Debian would be greatly appreciated. I think these scripts are very useful.

**Comment by jaylee79** [comment]
amotoki, take a look at:  https://choosealicense.com/  It describes various licenses.  I think MIT is typically recommended for simple and permissive use.

**Comment by amotoki** [comment]
Thanks for the advice and sorry late.
I finally could take time to compare various licenses.

**Comment by PeteLawler** [comment]
Hi there,
No worries about taking your time to compare licences. I greatly appreciate it as well as granting MIT licence.

Thanks so much.
